---
- hosts: all
  tasks:
     - name: Instalar Apache2
       apt:
         name: apache2
         state: latest
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
     - name: Instalar httpd
       yum:
         name: httpd
         state: latest
       when: "{{ansible_distribution=='CentOs'}}"
...
